create table warehouse (w_id int, w_name char(10), w_tax float);
create table customer (c_id int, c_d_id int, c_w_id int, c_last char(16), c_credit char(2), c_discount float);
create index warehouse(w_id);
create index customer(c_w_id, c_d_id, c_id);
insert into warehouse values (1, 'w1', 0.10);
insert into warehouse values (2, 'w2', 0.20);
insert into warehouse values (3, 'w3', 0.30);
insert into customer values (1, 1, 1, 'smith', 'GC', 0.05);
insert into customer values (2, 1, 1, 'brown', 'GC', 0.08);
insert into customer values (3, 1, 1, 'allen', 'BC', 0.12);
insert into customer values (4, 2, 1, 'clark', 'GC', 0.07);
insert into customer values (5, 1, 2, 'davis', 'BC', 0.09);
insert into customer values (6, 2, 2, 'evans', 'GC', 0.11);
insert into customer values (7, 1, 3, 'ford', 'GC', 0.04);
insert into customer values (8, 2, 3, 'green', 'BC', 0.06);
explain select c_discount, c_last, c_credit, w_tax from customer, warehouse where w_id = 1 and c_w_id = w_id and c_d_id = 1 and c_id = 3;
explain select c_discount, c_last, c_credit, w_tax from customer, warehouse where w_id = 1 and c_w_id = 1 and c_d_id = 1 and c_id = 3;
select c_discount, c_last, c_credit, w_tax from customer, warehouse where w_id = 1 and c_w_id = w_id and c_d_id = 1 and c_id = 3;
drop table customer;
drop table warehouse;
